version: '3.8'

services:
  postgresql:
    extends:
      file: docker-compose.base.yml
      service: postgresql
    networks:
      - project

  pgadmin:
    extends:
      file: docker-compose.base.yml
      service: pgadmin
    networks:
      - project

  app-server:
    depends_on:
      - postgresql
    build:
      context: ./
      dockerfile: DockerFile
      target: production
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    networks:
      - project
    env_file:
      - .env

volumes:
  db:
    driver: local
  pgadmin_data:
    driver: local

networks:
  project: